### ISSUE TITLE
Transition Nuget package to bandwidth user

### ISSUE THREAD

**Issue by scottbarstow** [bandwidthcom/csharp-bandwidth#14]
I created a new nuget user called bandwidth.  We need to transition ownership of the package to that user.

**Comment by dtolb** [comment]
@avbel is this still open?

**Comment by avbel** [comment]
![image](https://cloud.githubusercontent.com/assets/3050652/12549379/05fc2f10-c36e-11e5-839d-8d5449ba26eb.png)
