### ISSUE TITLE
Refactor SMS Event to Message event. Include sample of downloading media

### ISSUE THREAD

**Issue by dtolb** [bandwidthcom/csharp-bandwidth#16]
The use of SMSEvent has been deprecated. Everything is now defaulted to MessageEvent in order to hold the media parameter.

SDK needs to implement the Media parameter in a MessageEvent (similar to SmsEvent.cs but with the added media value).

Also, please provide sample code of downloading the Media for incoming MMS messages.

**Comment by dtolb** [comment]
@avbel let me know if you have any questions. Thanks!

**Comment by avbel** [comment]
No questions. I'll do that.

2015-12-18 19:38 GMT+03:00, Daniel Tolbert <notifications@github.com>:
