### ISSUE TITLE
Exception when media loading

### ISSUE THREAD

**Issue by JurySemerikov** [bandwidthcom/csharp-bandwidth#71]
```
using (var media = await client.Media.DownloadAsync(mediaName)) {
	var byteArray = await media.ReadAsByteArrayAsync(); // "The request was aborted: The request was canceled." exception here
}
```

DownloadMediaFileData contains HttpResponseMessage which was read by HttpClient with HttpCompletionOption.ResponseHeadersRead parameter. The HttpClient already disposed and we can't read content more.

**Comment by avbel** [comment]
Fixed in 3.1.2
